### ISSUE TITLE
Bug #01

### ISSUE THREAD

**Issue by marianasalcedo** [marianasalcedo/IWVG.SwC.MarianaSalcedo#7]
La funcionalidad de cacular si una Fraccion es impropia no está según la especificación explicada en: https://github.com/marianasalcedo/IWVG.SwC.MarianaSalcedo/wiki#fraction 

Por favor corregir la función y su prueba unitaria

**Comment by AlbertoMIW** [comment]
Ya tienes tu implementacion segun tu especificacion. 
https://github.com/marianasalcedo/IWVG.SwC.MarianaSalcedo/issues/5
Revisala

**Comment by marianasalcedo** [comment]
Listo! revisada!
